#!/usr/bin/env node
/**
 * Inline the stylesheet and script into a TypeScript module.
 *
 * The Workers Assets API is not available to this deployment's OAuth token, so
 * the two static files are served by the Worker itself instead. They are read
 * from the Python app's `web/static/` directory, which stays the single source
 * of truth -- this generates a build artifact, it does not fork the files.
 *
 * At ~23 KB for both, serving them from the Worker costs a negligible number
 * of invocations against the free plan's 100,000/day, and the browser caches
 * them by ETag after the first request.
 *
 *   node scripts/build-static.mjs
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const sourceDir = join(here, "..", "..", "flightnotify", "web", "static");
const outFile = join(here, "..", "src", "web", "static-assets.ts");

const read = (name) => readFileSync(join(sourceDir, name), "utf8");
const css = read("app.css");
const js = read("app.js");
const etag = (text) => createHash("sha256").update(text).digest("hex").slice(0, 16);

/** Escape for a TypeScript template literal. */
const literal = (text) => text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

writeFileSync(
  outFile,
  `/**
 * Generated by scripts/build-static.mjs from flightnotify/web/static/.
 * Do not edit: run \`npm run build:static\` after changing the source files.
 */

export const APP_CSS = \`${literal(css)}\`;
export const APP_JS = \`${literal(js)}\`;
export const APP_CSS_ETAG = "${etag(css)}";
export const APP_JS_ETAG = "${etag(js)}";
`,
);

console.log(
  `wrote src/web/static-assets.ts (css ${css.length} B, js ${js.length} B)`,
);
