"""bot poller lease

Revision ID: 556a52433918
Revises: d04fc4d3e969
Create Date: 2026-08-02 11:16:00.352859
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import flightnotify.jsontype  # noqa: F401  (custom column types in autogenerated DDL)

revision: str = '556a52433918'
down_revision: str | None = 'd04fc4d3e969'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_lock_owner', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('bot_lock_expires_at', flightnotify.jsontype.UtcDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_state', schema=None) as batch_op:
        batch_op.drop_column('bot_lock_expires_at')
        batch_op.drop_column('bot_lock_owner')

    # ### end Alembic commands ###
