"""initial schema

Revision ID: d04fc4d3e969
Revises: 
Create Date: 2026-08-01 18:16:26.714390
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import flightnotify.jsontype  # noqa: F401  (custom column types in autogenerated DDL)

revision: str = 'd04fc4d3e969'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', flightnotify.jsontype.JSONEncoded(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('provider_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=32), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_calls', schema=None) as batch_op:
        batch_op.create_index('ix_provider_calls_time', ['provider', 'called_at'], unique=False)

    op.create_table('provider_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('local_searches', sa.Integer(), nullable=False),
    sa.Column('provider_searches_per_month', sa.Integer(), nullable=True),
    sa.Column('provider_searches_left', sa.Integer(), nullable=True),
    sa.Column('provider_this_month_usage', sa.Integer(), nullable=True),
    sa.Column('provider_plan_name', sa.String(length=80), nullable=True),
    sa.Column('provider_account_email_masked', sa.String(length=120), nullable=True),
    sa.Column('provider_rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'period', name='uq_provider_period')
    )
    op.create_table('query_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=32), nullable=False),
    sa.Column('payload', flightnotify.jsontype.JSONEncoded(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_query_cache_fingerprint')
    )
    with op.batch_alter_table('query_cache', schema=None) as batch_op:
        batch_op.create_index('ix_query_cache_expiry', ['expires_at'], unique=False)

    op.create_table('scheduler_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lock_owner', sa.String(length=80), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tick_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('infants_in_seat', sa.Integer(), nullable=False),
    sa.Column('infants_on_lap', sa.Integer(), nullable=False),
    sa.Column('cabin', sa.String(length=20), nullable=False),
    sa.Column('stops', sa.String(length=16), nullable=False),
    sa.Column('include_airlines', sa.String(length=120), nullable=True),
    sa.Column('exclude_airlines', sa.String(length=120), nullable=True),
    sa.Column('date_mode', sa.String(length=20), nullable=False),
    sa.Column('outbound_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('flex_month', sa.Integer(), nullable=True),
    sa.Column('flex_year', sa.Integer(), nullable=True),
    sa.Column('flex_duration', sa.String(length=16), nullable=True),
    sa.Column('window_outbound_start', sa.Date(), nullable=True),
    sa.Column('window_outbound_end', sa.Date(), nullable=True),
    sa.Column('window_return_start', sa.Date(), nullable=True),
    sa.Column('window_return_end', sa.Date(), nullable=True),
    sa.Column('min_nights', sa.Integer(), nullable=True),
    sa.Column('max_nights', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('threshold_basis', sa.String(length=16), nullable=False),
    sa.Column('alert_on_threshold', sa.Boolean(), nullable=False),
    sa.Column('alert_on_new_low', sa.Boolean(), nullable=False),
    sa.Column('min_drop_absolute', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_drop_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('candidates_per_run', sa.Integer(), nullable=False),
    sa.Column('sampled_mode_ack', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('lock_owner', sa.String(length=80), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_config_version_id', sa.Integer(), nullable=True),
    sa.Column('series_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('latest_observation_id', sa.Integer(), nullable=True),
    sa.Column('latest_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low_observation_id', sa.Integer(), nullable=True),
    sa.Column('low_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_threshold_met', sa.Boolean(), nullable=False),
    sa.Column('coverage_cycle', sa.Integer(), nullable=False),
    sa.Column('last_error_category', sa.String(length=32), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('adults >= 1', name='ck_trackers_adults_min'),
    sa.CheckConstraint('check_interval_minutes >= 15', name='ck_trackers_interval_min'),
    sa.CheckConstraint('children >= 0', name='ck_trackers_children_min'),
    sa.CheckConstraint('threshold_amount > 0', name='ck_trackers_threshold_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trackers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trackers_current_config_version_id'), ['current_config_version_id'], unique=False)
        batch_op.create_index('ix_trackers_status_next_run', ['status', 'next_run_at'], unique=False)

    op.create_table('tracker_config_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('payload', flightnotify.jsontype.JSONEncoded(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracker_id', 'version', name='uq_config_version_number')
    )
    with op.batch_alter_table('tracker_config_versions', schema=None) as batch_op:
        batch_op.create_index('ix_config_versions_tracker_fp', ['tracker_id', 'fingerprint'], unique=False)

    op.create_table('tracker_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracker_id', 'market', name='uq_tracker_market')
    )
    op.create_table('flexible_date_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('config_version_id', sa.Integer(), nullable=False),
    sa.Column('outbound_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['config_version_id'], ['tracker_config_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_version_id', 'outbound_date', 'return_date', name='uq_candidate_pair')
    )
    with op.batch_alter_table('flexible_date_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_candidates_queue', ['config_version_id', 'cycle', 'status', 'order_index'], unique=False)

    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('config_version_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('endpoint', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('outbound_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider_request_count', sa.Integer(), nullable=False),
    sa.Column('cache_status', sa.String(length=16), nullable=False),
    sa.Column('coverage_cycle', sa.Integer(), nullable=True),
    sa.Column('coverage_state', sa.String(length=20), nullable=False),
    sa.Column('coverage_checked', sa.Integer(), nullable=True),
    sa.Column('coverage_total', sa.Integer(), nullable=True),
    sa.Column('offers_found', sa.Integer(), nullable=False),
    sa.Column('best_observation_id', sa.Integer(), nullable=True),
    sa.Column('error_category', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('raw_excerpt', flightnotify.jsontype.JSONEncoded(), nullable=True),
    sa.ForeignKeyConstraint(['config_version_id'], ['tracker_config_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_batch', ['batch_id'], unique=False)
        batch_op.create_index('ix_runs_fingerprint', ['query_fingerprint'], unique=False)
        batch_op.create_index('ix_runs_tracker_started', ['tracker_id', 'started_at'], unique=False)

    op.create_table('fare_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('config_version_id', sa.Integer(), nullable=True),
    sa.Column('itinerary_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_scope', sa.String(length=16), nullable=False),
    sa.Column('per_traveler_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('per_traveler_is_calculated', sa.Boolean(), nullable=False),
    sa.Column('party_total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('party_total_is_calculated', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=True),
    sa.Column('destination', sa.String(length=8), nullable=True),
    sa.Column('outbound_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('departure_time', sa.String(length=32), nullable=True),
    sa.Column('arrival_time', sa.String(length=32), nullable=True),
    sa.Column('airlines', flightnotify.jsontype.JSONEncoded(), nullable=True),
    sa.Column('flight_numbers', flightnotify.jsontype.JSONEncoded(), nullable=True),
    sa.Column('stops', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('cabin', sa.String(length=32), nullable=True),
    sa.Column('segments', flightnotify.jsontype.JSONEncoded(), nullable=True),
    sa.Column('layovers', flightnotify.jsontype.JSONEncoded(), nullable=True),
    sa.Column('booking_link', sa.Text(), nullable=True),
    sa.Column('search_link', sa.Text(), nullable=True),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=120), nullable=True),
    sa.Column('is_best_of_run', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['tracker_config_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fare_observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_run', ['search_run_id'], unique=False)
        batch_op.create_index('ix_obs_tracker_observed', ['tracker_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_obs_tracker_series_price', ['tracker_id', 'config_version_id', 'price_amount'], unique=False)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('config_version_id', sa.Integer(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=16), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('delivery_state', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('response_meta', flightnotify.jsontype.JSONEncoded(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['config_version_id'], ['tracker_config_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['observation_id'], ['fare_observations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_alert_dedupe_key')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_tracker_created', ['tracker_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_tracker_created')

    op.drop_table('alert_events')
    with op.batch_alter_table('fare_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_obs_tracker_series_price')
        batch_op.drop_index('ix_obs_tracker_observed')
        batch_op.drop_index('ix_obs_run')

    op.drop_table('fare_observations')
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_tracker_started')
        batch_op.drop_index('ix_runs_fingerprint')
        batch_op.drop_index('ix_runs_batch')

    op.drop_table('search_runs')
    with op.batch_alter_table('flexible_date_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_candidates_queue')

    op.drop_table('flexible_date_candidates')
    op.drop_table('tracker_markets')
    with op.batch_alter_table('tracker_config_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_config_versions_tracker_fp')

    op.drop_table('tracker_config_versions')
    with op.batch_alter_table('trackers', schema=None) as batch_op:
        batch_op.drop_index('ix_trackers_status_next_run')
        batch_op.drop_index(batch_op.f('ix_trackers_current_config_version_id'))

    op.drop_table('trackers')
    op.drop_table('scheduler_state')
    with op.batch_alter_table('query_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_query_cache_expiry')

    op.drop_table('query_cache')
    op.drop_table('provider_usage')
    with op.batch_alter_table('provider_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_provider_calls_time')

    op.drop_table('provider_calls')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
