/**
 * Parity with the Python implementation.
 *
 * These vectors are generated by `tests/golden/generate_vectors.py` from the
 * Python domain code, which remains the behavioural source of truth. CI
 * regenerates the file and fails on any diff, so this suite is what turns
 * "we ported it faithfully" into something a build can check.
 */

import { describe, expect, it } from "vitest";

import vectors from "./golden/vectors.json";
import { canonicalJson } from "../src/domain/canonical.js";
import {
  alertDedupeKey,
  configFingerprint,
  itineraryFingerprint,
  queryFingerprint,
} from "../src/domain/fingerprints.js";
import { decimalStringFromCents, formatMoney } from "../src/domain/money.js";
import { comparableCents, evaluate, normalizePrice } from "../src/domain/evaluation.js";
import type {
  PriceScopeValue,
  ThresholdBasisValue,
} from "../src/domain/enums.js";

describe("pricing parity", () => {
  for (const [index, v] of vectors.pricing.entries()) {
    it(`normalizes ${v.reported_cents}c as ${v.scope} for ${v.paying_travelers} (#${index})`, () => {
      const norm = normalizePrice(
        v.reported_cents,
        v.scope as PriceScopeValue,
        v.paying_travelers,
      );
      expect(norm.partyTotalCents).toBe(v.party_total_cents);
      expect(norm.partyTotalIsCalculated).toBe(v.party_total_is_calculated);
      expect(norm.perTravelerCents).toBe(v.per_traveler_cents);
      expect(norm.perTravelerIsCalculated).toBe(v.per_traveler_is_calculated);

      for (const [basis, expected] of Object.entries(v.comparable)) {
        expect(
          comparableCents(
            v.reported_cents,
            v.scope as PriceScopeValue,
            basis as ThresholdBasisValue,
            v.paying_travelers,
          ),
        ).toBe(expected);
      }
    });
  }
});

describe("format_money parity", () => {
  for (const v of vectors.format_money) {
    it(`renders ${v.amount_cents}c ${v.currency} as ${v.expected}`, () => {
      expect(formatMoney(v.amount_cents, v.currency)).toBe(v.expected);
    });
  }
});

describe("fingerprint parity", () => {
  for (const [index, v] of vectors.config_fingerprint.entries()) {
    it(`config fingerprint #${index}`, async () => {
      await expect(configFingerprint(v.payload as never)).resolves.toBe(v.expected);
    });
  }

  it("reproduces the live production tracker's series fingerprint", async () => {
    // Guards the import: a different digest would start a *new* comparison
    // series and orphan the imported price history.
    const production = vectors.config_fingerprint[0]!;
    await expect(configFingerprint(production.payload as never)).resolves.toBe(
      "49bfddc442c5bc9b90b95525dca32d9fcb6ae3f56c36dc48e69ed6c27a7a79df",
    );
  });

  it("drops null-valued keys, so they hash identically", async () => {
    const withNull = vectors.config_fingerprint[2]!;
    const without = vectors.config_fingerprint[3]!;
    expect(withNull.expected).toBe(without.expected);
    await expect(configFingerprint(withNull.payload as never)).resolves.toBe(
      without.expected,
    );
  });

  for (const [index, v] of vectors.query_fingerprint.entries()) {
    it(`query fingerprint #${index}`, async () => {
      await expect(queryFingerprint(v.endpoint, v.params as never)).resolves.toBe(v.expected);
    });
  }

  it("excludes the api key from the query fingerprint", async () => {
    // Two requests differing only in credentials and transport flags are the
    // same logical query: they must share a cache key, and the key must never
    // carry the secret.
    const base = { engine: "google_flights", departure_id: "SFO", arrival_id: "NRT" };
    const withSecret = { ...base, api_key: "SECRET-A", output: "json", no_cache: true };
    const withOther = { ...base, api_key: "SECRET-B", output: "html", no_cache: false };

    const a = await queryFingerprint("google_flights", withSecret);
    const b = await queryFingerprint("google_flights", withOther);
    expect(a).toBe(b);
    expect(a).toBe(await queryFingerprint("google_flights", base));
    expect(canonicalJson({ endpoint: "google_flights", params: base })).not.toContain("SECRET");
  });

  for (const [index, v] of vectors.itinerary_fingerprint.entries()) {
    it(`itinerary fingerprint #${index}`, async () => {
      await expect(itineraryFingerprint(v.args as never)).resolves.toBe(v.expected);
    });
  }
});

describe("alert dedupe key parity", () => {
  for (const [index, v] of vectors.alert_dedupe_key.entries()) {
    it(`dedupe key #${index}`, async () => {
      await expect(alertDedupeKey(v.args as never)).resolves.toBe(v.expected);
    });
  }

  it("collapses trailing-zero price representations to one key", async () => {
    // $1042 and $1042.00 are the same fare; two keys would alert twice.
    const [a, b] = [vectors.alert_dedupe_key[0]!, vectors.alert_dedupe_key[1]!];
    expect(a.expected).toBe(b.expected);
    await expect(alertDedupeKey(a.args as never)).resolves.toBe(
      await alertDedupeKey(b.args as never),
    );
  });
});

describe("decimal rendering parity", () => {
  it("matches Python's format(Decimal.normalize(), 'f')", () => {
    expect(decimalStringFromCents(196200)).toBe("1962");
    expect(decimalStringFromCents(130050)).toBe("1300.5");
    expect(decimalStringFromCents(1)).toBe("0.01");
    expect(decimalStringFromCents(10)).toBe("0.1");
    expect(decimalStringFromCents(0)).toBe("0");
    expect(decimalStringFromCents(-500)).toBe("-5");
  });
});

describe("evaluation parity", () => {
  for (const v of vectors.evaluation) {
    it(v.name, () => {
      const input = v.input;
      const result = evaluate({
        reportedCents: input.reported_cents,
        priceScope: input.scope as PriceScopeValue,
        thresholdCents: input.threshold_cents,
        thresholdBasis: input.basis as ThresholdBasisValue,
        payingTravelers: input.paying_travelers,
        state: {
          previousBestCents: input.state.previous_best_cents,
          seriesLowCents: input.state.series_low_cents,
          hasBaseline: input.state.has_baseline,
          previouslyMetThreshold: input.state.previously_met_threshold,
        },
        alertOnThreshold: input.alert_on_threshold,
        alertOnNewLow: input.alert_on_new_low,
        minDropAbsoluteCents: input.min_drop_absolute_cents,
        minDropPercentBp: input.min_drop_percent_bp,
      });

      expect(result.comparableCents).toBe(v.expected.comparable_cents);
      expect(result.isBaseline).toBe(v.expected.is_baseline);
      expect(result.meetsThreshold).toBe(v.expected.meets_threshold);
      expect(result.isNewLow).toBe(v.expected.is_new_low);
      expect(result.dropAbsoluteCents).toBe(v.expected.drop_absolute_cents);
      expect(result.dropPercentBp).toBe(v.expected.drop_percent_bp);
      expect(result.alertsToSend).toEqual(v.expected.alerts_to_send);
    });
  }
});
