/**
 * Telegram port behaviour.
 *
 * Every expected message string below was generated by running the Python
 * implementation (`flightnotify.services.messages`) and pasting its output
 * verbatim, so these assertions are parity checks rather than descriptions of
 * whatever the TypeScript happens to do.
 *
 * No test may reach the network: the bot these credentials are shaped like is in
 * production use, and a stray sendMessage would arrive on a real person's phone.
 * `beforeEach` therefore replaces the global fetch with one that throws, so an
 * un-stubbed call fails loudly instead of dialling out.
 */

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { AlertType, PriceScopeLabel, ThresholdBasis } from "../src/domain/enums.js";
import {
  buildAlertText,
  buildTestMessage,
  coverageSentence,
  dateRange,
  type AlertContext,
} from "../src/services/messages.js";
import {
  TelegramNotifier,
  escapeHtml,
  isRetryable,
  type FetchLike,
  type TelegramCategory,
  type TelegramConfig,
} from "../src/services/telegram.js";

/** Obviously fake, but shaped like a real token so redaction is exercised. */
const FAKE_TOKEN = "123456789:TESTTOKEN-not-real-aaaaaaaaaaaaaaaaaaaaaaa";
const TOKEN_SECRET = FAKE_TOKEN.split(":")[1]!;

const CONFIG: TelegramConfig = {
  telegramBotToken: FAKE_TOKEN,
  telegramChatId: "987",
  telegramBaseUrl: "https://api.telegram.org",
};

const TZ = "America/Los_Angeles";
const OBSERVED_AT = new Date("2026-10-02T22:17:00Z");

interface RecordedCall {
  url: string;
  body: URLSearchParams;
  hasSignal: boolean;
}

/** A fetch that answers with one JSON body and records what it was asked. */
function jsonFetch(body: unknown, status = 200) {
  const calls: RecordedCall[] = [];
  const fetchImpl: FetchLike = async (url, init) => {
    calls.push({
      url,
      body: new URLSearchParams(String(init.body ?? "")),
      hasSignal: init.signal !== undefined && init.signal !== null,
    });
    return new Response(JSON.stringify(body), {
      status,
      headers: { "content-type": "application/json" },
    });
  };
  return { fetchImpl, calls };
}

/** A fetch that fails the way a runtime signals a transport problem. */
function throwingFetch(name: string): FetchLike {
  return async () => {
    const error = new Error("request failed");
    error.name = name;
    throw error;
  };
}

function notifier(body: unknown, status = 200) {
  const { fetchImpl, calls } = jsonFetch(body, status);
  return { client: new TelegramNotifier(CONFIG, { fetch: fetchImpl }), calls };
}

beforeEach(() => {
  vi.stubGlobal("fetch", () => {
    throw new Error("a test tried to use the real network");
  });
});

afterEach(() => {
  vi.unstubAllGlobals();
});

// --------------------------------------------------------------- escaping
describe("escapeHtml", () => {
  it("escapes only the three characters Telegram requires", () => {
    // html.escape(text, quote=False): quotes and apostrophes stay literal.
    expect(escapeHtml(`& < > " '`)).toBe(`&amp; &lt; &gt; " '`);
  });

  it("matches the Python fixture", () => {
    expect(escapeHtml("Fly <SFO> & save")).toBe("Fly &lt;SFO&gt; &amp; save");
  });

  it("does not double-escape the ampersands it introduces", () => {
    expect(escapeHtml("<b>")).toBe("&lt;b&gt;");
    expect(escapeHtml("&amp;")).toBe("&amp;amp;");
  });

  it("leaves an apostrophe alone so it does not render as &#x27;", () => {
    expect(escapeHtml("Kay's trip")).toBe("Kay's trip");
  });
});

// -------------------------------------------------------- error categories
describe("error classification", () => {
  const cases: Array<{
    name: string;
    status: number;
    body: Record<string, unknown>;
    category: TelegramCategory;
    phrase: string;
  }> = [
    {
      name: "401 is an invalid token",
      status: 401,
      body: { error_code: 401, description: "Unauthorized" },
      category: "invalid_token",
      phrase: "bot token",
    },
    {
      name: "an unauthorized description wins without a 401 code",
      status: 400,
      body: { description: "Unauthorized: bot token is wrong" },
      category: "invalid_token",
      phrase: "bot token",
    },
    {
      name: "429 is a rate limit",
      status: 429,
      body: {
        error_code: 429,
        description: "Too Many Requests: retry after 7",
        parameters: { retry_after: 7 },
      },
      category: "rate_limit",
      phrase: "retry after 7s",
    },
    {
      name: "403 is a blocked chat",
      status: 403,
      body: { error_code: 403, description: "Forbidden: bot was blocked by the user" },
      category: "blocked",
      phrase: "/start",
    },
    {
      name: "chat not found is matched on the description",
      status: 400,
      body: { error_code: 400, description: "Bad Request: chat not found" },
      category: "chat_not_found",
      phrase: "chat id",
    },
    {
      name: "5xx is a server error",
      status: 500,
      body: { error_code: 500, description: "Internal Server Error" },
      category: "server_error",
      phrase: "retried",
    },
    {
      name: "anything else is a generic error carrying the description",
      status: 400,
      body: { error_code: 400, description: "Bad Request: message text is empty" },
      category: "error",
      phrase: "message text is empty",
    },
  ];

  for (const testCase of cases) {
    it(testCase.name, async () => {
      const { client } = notifier({ ok: false, ...testCase.body }, testCase.status);
      const result = await client.sendMessage("987", "hello");
      expect(result.ok).toBe(false);
      expect(result.category).toBe(testCase.category);
      expect(result.userMessage).toContain(testCase.phrase);
    });
  }

  it("classification order puts 401 ahead of the 403 keyword test", async () => {
    // "Unauthorized" and "forbidden" can both appear; the Python checks
    // unauthorized first, so a token problem is never reported as a block.
    const { client } = notifier(
      { ok: false, error_code: 401, description: "Unauthorized: forbidden token" },
      401,
    );
    expect((await client.sendMessage("987", "hi")).category).toBe("invalid_token");
  });

  it("carries error_code, description and retry_after through", async () => {
    const { client } = notifier(
      {
        ok: false,
        error_code: 429,
        description: "Too Many Requests: retry after 7",
        parameters: { retry_after: 7 },
      },
      429,
    );
    const result = await client.sendMessage("987", "hello");
    expect(result.errorCode).toBe(429);
    expect(result.description).toBe("Too Many Requests: retry after 7");
    expect(result.retryAfter).toBe(7);
  });

  it("omits the retry hint when Telegram supplies no retry_after", async () => {
    const { client } = notifier(
      { ok: false, error_code: 429, description: "Too Many Requests" },
      429,
    );
    const result = await client.sendMessage("987", "hello");
    expect(result.retryAfter).toBeNull();
    expect(result.userMessage).toBe(
      "Telegram rate-limited the bot. The price observation is saved and the alert will be retried.",
    );
  });

  it("falls back to the HTTP status when the body carries no detail", async () => {
    const { client } = notifier({ ok: false }, 502);
    const result = await client.sendMessage("987", "hello");
    expect(result.description).toBe("HTTP 502");
    expect(result.errorCode).toBe(502);
    expect(result.category).toBe("server_error");
  });

  it("treats a non-JSON body as no body at all", async () => {
    const fetchImpl: FetchLike = async () => new Response("<html>gateway</html>", { status: 503 });
    const client = new TelegramNotifier(CONFIG, { fetch: fetchImpl });
    const result = await client.sendMessage("987", "hello");
    expect(result.category).toBe("server_error");
    expect(result.description).toBe("HTTP 503");
  });

  it("reports a timed-out request as a timeout", async () => {
    const client = new TelegramNotifier(CONFIG, { fetch: throwingFetch("TimeoutError") });
    const result = await client.sendMessage("987", "hello");
    expect(result.category).toBe("timeout");
    expect(result.userMessage).toContain("still saved");
  });

  it("reports any other transport failure as a network error", async () => {
    const client = new TelegramNotifier(CONFIG, { fetch: throwingFetch("TypeError") });
    const result = await client.sendMessage("987", "hello");
    expect(result.category).toBe("network");
    expect(result.userMessage).toContain("(TypeError)");
  });

  it("refuses to call at all when no token is configured", async () => {
    const fetchImpl = vi.fn<FetchLike>();
    const client = new TelegramNotifier(
      { ...CONFIG, telegramBotToken: "   " },
      { fetch: fetchImpl },
    );
    const result = await client.sendMessage("1", "hello");
    expect(result.category).toBe("not_configured");
    expect(result.userMessage).toContain("BotFather");
    expect(fetchImpl).not.toHaveBeenCalled();
  });
});

describe("retryable", () => {
  it("is exactly the four transient categories", () => {
    const categories: TelegramCategory[] = [
      "ok",
      "not_configured",
      "invalid_token",
      "rate_limit",
      "blocked",
      "chat_not_found",
      "server_error",
      "timeout",
      "network",
      "no_chats",
      "error",
    ];
    const retryable = categories.filter(isRetryable).sort();
    expect(retryable).toEqual(["network", "rate_limit", "server_error", "timeout"]);
  });

  it("is exposed on the result so callers never re-derive it", async () => {
    const { client } = notifier({ ok: false, error_code: 500, description: "Internal" }, 500);
    expect((await client.sendMessage("987", "x")).retryable).toBe(true);

    const blocked = notifier({ ok: false, error_code: 403, description: "Forbidden" }, 403);
    expect((await blocked.client.sendMessage("987", "x")).retryable).toBe(false);
  });
});

// ------------------------------------------------------------ token safety
describe("bot token handling", () => {
  it("puts the token in the URL path and nowhere in the result", async () => {
    const { client, calls } = notifier(
      { ok: false, error_code: 401, description: "Unauthorized" },
      401,
    );
    const result = await client.sendMessage("987", "hello");

    expect(calls[0]!.url).toBe(`https://api.telegram.org/bot${FAKE_TOKEN}/sendMessage`);
    expect(result.userMessage).not.toContain(TOKEN_SECRET);
    expect(result.userMessage).not.toContain(FAKE_TOKEN);
    expect(result.description).not.toContain(TOKEN_SECRET);
    expect(JSON.stringify(result)).not.toContain(TOKEN_SECRET);
  });

  it("redacts a token echoed back inside a Telegram description", async () => {
    const { client } = notifier(
      { ok: false, error_code: 400, description: `Bad Request at /bot${FAKE_TOKEN}/sendMessage` },
      400,
    );
    const result = await client.sendMessage("987", "hello");
    expect(result.description).toBe("Bad Request at /bot[redacted]/sendMessage");
    expect(JSON.stringify(result)).not.toContain(TOKEN_SECRET);
  });

  it("never puts a transport error's own message into the result", async () => {
    const leaky: FetchLike = async () => {
      throw new TypeError(`fetch to https://api.telegram.org/bot${FAKE_TOKEN}/getMe failed`);
    };
    const client = new TelegramNotifier(CONFIG, { fetch: leaky });
    const result = await client.getMe();
    expect(JSON.stringify(result)).not.toContain(TOKEN_SECRET);
    expect(result.userMessage).toContain("(TypeError)");
  });

  it("hints at the bot id without revealing the token", () => {
    const client = new TelegramNotifier(CONFIG);
    expect(client.tokenHint()).toBe("bot id 123456789");
    expect(client.tokenHint()).not.toContain(TOKEN_SECRET);
  });

  it("reports a null hint when nothing is configured, and a neutral one when malformed", () => {
    expect(new TelegramNotifier({ ...CONFIG, telegramBotToken: "" }).tokenHint()).toBeNull();
    expect(new TelegramNotifier({ ...CONFIG, telegramBotToken: "junk" }).tokenHint()).toBe(
      "token loaded",
    );
  });
});

// -------------------------------------------------------------- API calls
describe("getMe", () => {
  it("reports the handle from the username", async () => {
    const { client, calls } = notifier({
      ok: true,
      result: { id: 1, is_bot: true, username: "flightnotify_bot" },
    });
    const result = await client.getMe();
    expect(result.ok).toBe(true);
    expect(result.userMessage).toBe("Connected as @flightnotify_bot.");
    expect(calls[0]!.url.endsWith("/getMe")).toBe(true);
    expect(calls[0]!.hasSignal).toBe(true);
  });

  it("falls back to the bot id when there is no username", async () => {
    const { client } = notifier({ ok: true, result: { id: 42, is_bot: true } });
    expect((await client.getMe()).userMessage).toBe("Connected as bot 42.");
  });

  it("passes an API failure straight through", async () => {
    const { client } = notifier({ ok: false, error_code: 401, description: "Unauthorized" }, 401);
    expect((await client.getMe()).category).toBe("invalid_token");
  });
});

describe("sendMessage", () => {
  it("returns the delivered message id", async () => {
    const { client, calls } = notifier({
      ok: true,
      result: { message_id: 42, chat: { id: 987 } },
    });
    const result = await client.sendMessage("987", "hello <b>world</b>");

    expect(result.ok).toBe(true);
    expect(result.messageId).toBe(42);
    expect(result.userMessage).toBe("Message delivered.");
    expect(result.meta["chatId"]).toBe(987);

    const sent = calls[0]!.body;
    expect(calls[0]!.url.endsWith("/sendMessage")).toBe(true);
    expect(sent.get("chat_id")).toBe("987");
    expect(sent.get("text")).toBe("hello <b>world</b>");
    expect(sent.get("parse_mode")).toBe("HTML");
    expect(sent.get("link_preview_options")).toBeNull();
  });

  it("disables the link preview only when asked", async () => {
    const { client, calls } = notifier({ ok: true, result: { message_id: 1, chat: { id: 1 } } });
    await client.sendMessage(987, "hi", { disablePreview: true });
    expect(calls[0]!.body.get("link_preview_options")).toBe('{"is_disabled":true}');
  });

  it("uses the global fetch when none is injected", async () => {
    const seen: string[] = [];
    vi.stubGlobal("fetch", async (url: string) => {
      seen.push(url);
      return new Response(JSON.stringify({ ok: true, result: { message_id: 7, chat: { id: 1 } } }));
    });
    const result = await new TelegramNotifier(CONFIG).sendMessage("987", "hi");
    expect(result.messageId).toBe(7);
    expect(seen).toHaveLength(1);
  });
});

describe("getUpdates", () => {
  it("sends the offset when one is supplied", async () => {
    const { client, calls } = notifier({ ok: true, result: [] });
    await client.getUpdates({ offset: 55, timeout: 25 });
    const sent = calls[0]!.body;
    expect(sent.get("offset")).toBe("55");
    expect(sent.get("timeout")).toBe("25");
    expect(sent.get("allowed_updates")).toBe('["message"]');
  });

  it("omits the offset entirely when there is none to confirm", async () => {
    const { client, calls } = notifier({ ok: true, result: [] });
    await client.getUpdates();
    expect(calls[0]!.body.has("offset")).toBe(false);
    expect(calls[0]!.body.get("timeout")).toBe("0");
  });

  it("returns the raw update list in meta", async () => {
    const { client } = notifier({ ok: true, result: [{ update_id: 9 }] });
    const result = await client.getUpdates({ offset: 9 });
    expect(result.ok).toBe(true);
    expect(result.meta["result"]).toEqual([{ update_id: 9 }]);
  });
});

describe("discoverChats", () => {
  const privateUpdate = (id: number, date: number, name: string, username?: string) => ({
    update_id: id,
    message: {
      message_id: id,
      date,
      text: "/start",
      chat: { id, type: "private", first_name: name, ...(username ? { username } : {}) },
    },
  });

  it("explains a missing /start rather than reporting a failure", async () => {
    const { client } = notifier({ ok: true, result: [] });
    const { chats, result } = await client.discoverChats();
    expect(chats).toEqual([]);
    expect(result.ok).toBe(false);
    expect(result.category).toBe("no_chats");
    expect(result.userMessage).toBe(
      "No recent direct chat was found. Open Telegram, send /start to your bot, then " +
        "try again. Telegram only keeps updates for 24 hours, and this will not work " +
        "if the bot has a webhook configured.",
    );
  });

  it("keeps private chats and drops groups, supergroups and channels", async () => {
    const { client } = notifier({
      ok: true,
      result: [
        privateUpdate(987, 1785000000, "Kay", "kay"),
        {
          update_id: 2,
          message: {
            message_id: 2,
            date: 1785000100,
            text: "hi",
            chat: { id: -100123, type: "supergroup", title: "Travel" },
          },
        },
        {
          update_id: 3,
          message: {
            message_id: 3,
            date: 1785000200,
            text: "hi",
            chat: { id: -200, type: "group", title: "Family" },
          },
        },
        {
          update_id: 4,
          message: {
            message_id: 4,
            date: 1785000300,
            chat: { id: -300, type: "channel", title: "Deals" },
          },
        },
      ],
    });

    const { chats, result } = await client.discoverChats();
    expect(result.ok).toBe(true);
    expect(chats.map((c) => c.chatId)).toEqual([987]);
    expect(chats[0]!.displayName).toBe("Kay (@kay)");
    expect(chats[0]!.lastText).toBe("/start");
    expect(chats[0]!.lastMessageAt?.toISOString()).toBe(new Date(1785000000000).toISOString());
  });

  it("orders newest first and collapses repeat messages from one chat", async () => {
    const { client } = notifier({
      ok: true,
      result: [
        privateUpdate(111, 1785000000, "Older"),
        privateUpdate(222, 1785009999, "Newer"),
        privateUpdate(111, 1785000500, "Older"),
      ],
    });
    const { chats } = await client.discoverChats();
    expect(chats.map((c) => c.chatId)).toEqual([222, 111]);
    // The chat appeared twice; the newest of its messages is what is kept.
    expect(chats[1]!.lastMessageAt?.getTime()).toBe(1785000500 * 1000);
  });

  it("names a chat by its id when Telegram gives no name at all", async () => {
    const { client } = notifier({
      ok: true,
      result: [{ update_id: 1, message: { message_id: 1, chat: { id: 55, type: "private" } } }],
    });
    const { chats } = await client.discoverChats();
    expect(chats[0]!.displayName).toBe("chat 55");
    expect(chats[0]!.lastMessageAt).toBeNull();
    expect(chats[0]!.lastText).toBeNull();
  });

  it("clamps the requested limit to Telegram's range", async () => {
    const { client, calls } = notifier({ ok: true, result: [] });
    await client.discoverChats(5000);
    expect(calls[0]!.body.get("limit")).toBe("100");

    const zero = notifier({ ok: true, result: [] });
    await zero.client.discoverChats(0);
    expect(zero.calls[0]!.body.get("limit")).toBe("1");
  });

  it("propagates an API failure instead of claiming no chats exist", async () => {
    const { client } = notifier({ ok: false, error_code: 401, description: "Unauthorized" }, 401);
    const { chats, result } = await client.discoverChats();
    expect(chats).toEqual([]);
    expect(result.category).toBe("invalid_token");
  });
});

// --------------------------------------------------------------- messages
const BASE_CONTEXT: AlertContext = {
  alertType: AlertType.THRESHOLD,
  trackerName: "Tokyo trip",
  origin: "SFO",
  destination: "NRT",
  passengerSummary: "2 adults",
  cabin: "economy",
  currency: "USD",
  comparableCents: 124800,
  thresholdCents: 130000,
  thresholdBasis: ThresholdBasis.PARTY,
  priceScope: PriceScopeLabel.PARTY_TOTAL,
  outboundDate: "2026-10-12",
  returnDate: "2026-10-20",
  stops: 0,
  market: "us",
  observedAt: OBSERVED_AT,
  previousLowCents: null,
  dropAbsoluteCents: null,
  isBaseline: true,
  coverageChecked: null,
  coverageTotal: null,
  coverageComplete: false,
  link: "https://www.google.com/travel/flights?q=SFO+NRT",
  airlines: ["ANA", "United"],
};

describe("buildAlertText", () => {
  it("renders a baseline threshold alert exactly as Python does", () => {
    expect(buildAlertText(BASE_CONTEXT, TZ)).toBe(
      "<b>✈️ Threshold reached — SFO → NRT</b>\n" +
        "Tokyo trip\n" +
        "\n" +
        "$1,248 total for 2 adults · Economy\n" +
        "Oct 12–20 · Nonstop · ANA, United · US market\n" +
        "First observation for this configuration — recorded as the baseline, not a price drop.\n" +
        "Threshold: $1,300 (whole party)\n" +
        "Checked: Oct 2, 3:17 PM PDT\n" +
        "\n" +
        '<a href="https://www.google.com/travel/flights?q=SFO+NRT">' +
        "Open this search on Google Flights</a>\n" +
        "\n" +
        "<i>Price and availability can change before booking.</i>",
    );
  });

  it("renders a new low with the previous low, the drop and partial coverage", () => {
    const text = buildAlertText(
      {
        ...BASE_CONTEXT,
        alertType: AlertType.NEW_LOW,
        trackerName: "Kay & co <VIP>",
        comparableCents: 110650,
        previousLowCents: 124800,
        dropAbsoluteCents: 14150,
        isBaseline: false,
        stops: 1,
        coverageChecked: 18,
        coverageTotal: 24,
        coverageComplete: false,
        link: null,
        airlines: [],
      },
      TZ,
    );

    expect(text).toBe(
      "<b>✈️ New observed low — SFO → NRT</b>\n" +
        "Kay &amp; co &lt;VIP&gt;\n" +
        "\n" +
        "$1,106.50 total for 2 adults · Economy\n" +
        "Oct 12–20 · 1 stop · US market\n" +
        "Previous observed low: $1,248 · down $141.50\n" +
        "Threshold: $1,300 (whole party)\n" +
        "Checked: Oct 2, 3:17 PM PDT\n" +
        "Lowest observed among 18 of 24 date combinations checked.\n" +
        "\n" +
        "<i>Price and availability can change before booking.</i>",
    );
    // No link was supplied, so none is invented.
    expect(text).not.toContain("<a href");
  });

  it("labels an unconfirmed price basis and caps the airline list at three", () => {
    expect(
      buildAlertText(
        {
          ...BASE_CONTEXT,
          priceScope: PriceScopeLabel.UNKNOWN,
          thresholdBasis: ThresholdBasis.PER_TRAVELER,
          isBaseline: false,
          previousLowCents: 124800,
          dropAbsoluteCents: 0,
          returnDate: null,
          stops: null,
          cabin: "premium_economy",
          coverageChecked: 24,
          coverageTotal: 24,
          coverageComplete: true,
          link: null,
          airlines: ["ANA", "United", "JAL", "Delta"],
          market: "jp",
        },
        TZ,
      ),
    ).toBe(
      "<b>✈️ Threshold reached — SFO → NRT</b>\n" +
        "Tokyo trip\n" +
        "\n" +
        "$1,248 as reported by the provider (price basis unconfirmed) · Premium economy\n" +
        "Oct 12 · Stops unknown · ANA, United, JAL · JP market\n" +
        "Previous observed low: $1,248\n" +
        "Threshold: $1,300 (per traveler)\n" +
        "Checked: Oct 2, 3:17 PM PDT\n" +
        "Lowest across all 24 date combinations in this cycle.\n" +
        "\n" +
        "<i>Price and availability can change before booking.</i>",
    );
  });

  it("never calls a baseline a drop, even when a drop was computed", () => {
    const text = buildAlertText(
      { ...BASE_CONTEXT, isBaseline: true, previousLowCents: 130000, dropAbsoluteCents: 5200 },
      TZ,
    );
    expect(text).toContain("baseline");
    expect(text).not.toContain("down $");
  });

  it("escapes the link href as well as the visible text", () => {
    const text = buildAlertText(
      { ...BASE_CONTEXT, link: "https://example.test/?a=1&b=2<x>" },
      TZ,
    );
    expect(text).toContain('<a href="https://example.test/?a=1&amp;b=2&lt;x&gt;">');
  });

  it("titles an unrecognised cabin the way Python's str.title does", () => {
    expect(buildAlertText({ ...BASE_CONTEXT, cabin: "premium_flex" }, TZ)).toContain(
      "· Premium_Flex",
    );
  });

  it("renders the checked-at line in the configured timezone", () => {
    expect(buildAlertText(BASE_CONTEXT, "Asia/Tokyo")).toContain("Checked: Oct 3, 7:17 AM GMT+9");
  });

  it("is presentation only, so it can never serve as a dedupe surface", () => {
    // The same fare observed twice renders two different bodies, because the
    // checked-at line moves. Dedupe therefore has to key off the domain values
    // (see alertDedupeKey), never off this text.
    const later = { ...BASE_CONTEXT, observedAt: new Date("2026-10-02T23:17:00Z") };
    expect(buildAlertText(later, TZ)).not.toBe(buildAlertText(BASE_CONTEXT, TZ));

    // Conversely, a formatting-only difference in the input renders identically:
    // trailing-zero cents are one fare, not two.
    expect(buildAlertText({ ...BASE_CONTEXT, comparableCents: 124800 }, TZ)).toBe(
      buildAlertText(BASE_CONTEXT, TZ),
    );
  });
});

describe("buildTestMessage", () => {
  it("matches Python and mentions no fare data", () => {
    expect(buildTestMessage(TZ, OBSERVED_AT)).toBe(
      "<b>✈️ FlightNotify test message</b>\n" +
        "If you can read this, alerts are wired up correctly. This message contains no fare data.\n" +
        "Sent: Oct 2, 3:17 PM PDT",
    );
  });
});

describe("dateRange", () => {
  it("matches every Python branch", () => {
    expect(dateRange("2026-10-12", "2026-10-20")).toBe("Oct 12–20");
    expect(dateRange("2026-10-12", "2026-11-03")).toBe("Oct 12–Nov 3");
    // An incoherent pair must not render as the tidy "Oct 12-8".
    expect(dateRange("2026-10-12", "2026-10-08")).toBe("Oct 12, 2026 → Oct 8, 2026");
    expect(dateRange("2026-10-12", null)).toBe("Oct 12");
    expect(dateRange(null, "2026-11-03")).toBe("Nov 3");
    expect(dateRange(null, null)).toBe("Dates from provider");
  });

  it("spells out a same-day-number pair in different years", () => {
    expect(dateRange("2026-10-12", "2027-10-12")).toBe("Oct 12–Oct 12");
  });
});

describe("coverageSentence", () => {
  it("never calls a partial scan complete", () => {
    expect(coverageSentence(18, 24, false)).toBe(
      "Lowest observed among 18 of 24 date combinations checked.",
    );
    expect(coverageSentence(24, 24, true)).toBe(
      "Lowest across all 24 date combinations in this cycle.",
    );
    // Claimed complete but short of the total: still described as partial.
    expect(coverageSentence(20, 24, true)).toBe(
      "Lowest observed among 20 of 24 date combinations checked.",
    );
    expect(coverageSentence(null, 24, false)).toBe("Partial scan of 24 date combinations.");
  });

  it("says nothing when there was only ever one combination", () => {
    expect(coverageSentence(null, 1, true)).toBe("");
    expect(coverageSentence(1, null, true)).toBe("");
    expect(coverageSentence(1, 0, true)).toBe("");
  });
});
